import type { Material, User, DonationRequest } from "./types"

// Datos mock para desarrollo
export const mockUsers: User[] = [
  {
    id: "1",
    email: "constructora@ejemplo.com",
    name: "Juan Pérez",
    role: "empresa",
  },
  {
    id: "2",
    email: "ong@ejemplo.com",
    name: "María García",
    role: "ong",
  },
  {
    id: "3",
    email: "voluntario@ejemplo.com",
    name: "Carlos López",
    role: "voluntario",
  },
]

export const mockMaterials: Material[] = [
  {
    id: "1",
    name: "Ladrillos de demolición",
    description:
      "Ladrillos en buen estado de demolición de edificio residencial. Aproximadamente 500 unidades disponibles.",
    category: "ladrillos",
    quantity: 500,
    unit: "unidades",
    condition: "usado-bueno",
    images: ["/ladrillos-de-construcci-n-apilados.jpg"],
    companyId: "1",
    companyName: "Constructora ABC",
    location: "Calle Mayor 123, Madrid",
    coordinates: { lat: 40.4168, lng: -3.7038 },
    availableFrom: "2024-12-09T09:00:00Z",
    status: "disponible",
    createdAt: "2024-12-09T09:00:00Z",
  },
  {
    id: "2",
    name: "Vigas de madera",
    description:
      "Vigas de madera maciza de roble, 3 metros de longitud. Ideales para proyectos de construcción sostenible.",
    category: "madera",
    quantity: 15,
    unit: "unidades",
    condition: "usado-excelente",
    images: ["/vigas-de-madera-apiladas-en-obra.jpg"],
    companyId: "1",
    companyName: "Constructora ABC",
    location: "Avenida de la Construcción 45, Barcelona",
    coordinates: { lat: 41.3851, lng: 2.1734 },
    availableFrom: "2024-12-08T14:30:00Z",
    status: "disponible",
    createdAt: "2024-12-08T14:30:00Z",
  },
  {
    id: "3",
    name: "Tubería de PVC",
    description: "Tubería de PVC de diferentes diámetros (110mm, 160mm). Sobrante de instalación de saneamiento.",
    category: "otros",
    quantity: 200,
    unit: "metros",
    condition: "usado-bueno",
    images: ["/tuber-a-pvc-construcci-n.jpg"],
    companyId: "1",
    companyName: "Constructora ABC",
    location: "Polígono Industrial Norte, Nave 7, Valencia",
    coordinates: { lat: 39.4699, lng: -0.3763 },
    availableFrom: "2024-12-07T11:15:00Z",
    status: "disponible",
    createdAt: "2024-12-07T11:15:00Z",
  },
  {
    id: "4",
    name: "Cemento Portland",
    description: "Sacos de cemento Portland en excelente estado. Ideal para construcción de cimientos y estructuras.",
    category: "cemento",
    quantity: 50,
    unit: "bolsas",
    condition: "nuevo",
    images: [],
    companyId: "1",
    companyName: "Constructora ABC",
    location: "Obra Residencial Los Pinos, Sevilla",
    coordinates: { lat: 37.3886, lng: -5.9823 },
    availableFrom: "2024-12-10T08:00:00Z",
    status: "disponible",
    createdAt: "2024-12-10T08:00:00Z",
  },
  {
    id: "5",
    name: "Azulejos cerámicos",
    description: "Azulejos cerámicos blancos 20x20cm. Sobrante de reforma de baño.",
    category: "ceramicos",
    quantity: 120,
    unit: "m2",
    condition: "nuevo",
    images: [],
    companyId: "1",
    companyName: "Constructora ABC",
    location: "Reforma Centro Comercial, Bilbao",
    coordinates: { lat: 43.2627, lng: -2.9253 },
    availableFrom: "2024-12-05T12:00:00Z",
    status: "disponible",
    createdAt: "2024-12-05T12:00:00Z",
  },
]

export const mockRequests: DonationRequest[] = [
  {
    id: "1",
    materialId: "1",
    ongId: "2",
    ongName: "Fundación Construir Futuro",
    requestedQuantity: 300,
    message:
      "Necesitamos estos ladrillos para un proyecto de vivienda social en el barrio de Vallecas. Estamos construyendo 5 casas para familias de escasos recursos. ¿Podríamos coordinar la recogida para el miércoles de la próxima semana?",
    status: "pendiente",
    requestDate: "2024-12-09T15:30:00Z",
  },
  {
    id: "2",
    materialId: "2",
    ongId: "2",
    ongName: "Fundación Construir Futuro",
    requestedQuantity: 8,
    message:
      "Estas vigas serían perfectas para el techo de una casa que estamos construyendo. Tenemos disponibilidad los fines de semana para la recogida.",
    status: "aprobada",
    requestDate: "2024-12-08T10:15:00Z",
    responseDate: "2024-12-08T16:20:00Z",
    pickupDate: "2024-12-14T09:00:00Z",
  },
  {
    id: "3",
    materialId: "4",
    ongId: "2",
    ongName: "Fundación Construir Futuro",
    requestedQuantity: 25,
    message:
      "Necesitamos cemento para los cimientos de un nuevo proyecto. ¿Sería posible coordinar la entrega directamente en obra?",
    status: "pendiente",
    requestDate: "2024-12-10T09:45:00Z",
  },
]

// Datos adicionales para compatibilidad
export const materialCategories = [
  { value: "all", label: "Todas las categorías" },
  { value: "cemento", label: "Cemento y Mortero" },
  { value: "ladrillos", label: "Ladrillos y Bloques" },
  { value: "hierro", label: "Hierro y Acero" },
  { value: "madera", label: "Madera" },
  { value: "ceramicos", label: "Cerámicos y Azulejos" },
  { value: "sanitarios", label: "Sanitarios" },
  { value: "electricidad", label: "Material Eléctrico" },
  { value: "pintura", label: "Pintura y Acabados" },
  { value: "otros", label: "Otros" },
]
